### ISSUE TITLE
For YT Goal Bar - Field Data JSON File for YouTube is not working with StreamElements

### ISSUE THREAD

**Issue by JHeroGR** [pjonp/pjTestBot#4]
When I copy and paste the data provided in the JSON file, Field Data for YouTube, the Goal Bar doesn't update nor does it even render, also the SE fields break and dump out garbage data from the JSON file itself. I fully copied the file from beginning to end and this has also not fixed the solution.

![image](https://user-images.githubusercontent.com/32202517/134616330-2307c018-8f58-4b4c-8c43-ab50a3c8c84a.png)
![image](https://user-images.githubusercontent.com/32202517/134616351-7e61d04d-9dfd-42d6-a089-069f911c83ca.png)
![image](https://user-images.githubusercontent.com/32202517/134616370-e1f6fb62-5895-4361-a5b2-1a3374935cbd.png)

**Comment by pjonp** [comment]
I just checked the widget and am not seeing any issue. I even created a new custom widget and copied all of the code over but am unable to replicate the issue you are showing in the images attached. Check if clearing the DATA tab works, change it to just {}

If you are still having issues give me a shout on Discord in the StreamElements server.
