### ISSUE TITLE
Bot Message to Chat is not working

### ISSUE THREAD

**Issue by blinddesecrator** [pjonp/pjTestBot#8]
It appears that with the update to Twitch's API it may have broken something for announcing the person in chat. I tested through jebaited.net and through the wheels themselves and everything is set up correctly. Can you confirm this issue?

**Comment by pjonp** [comment]
It may have been an issue between the Twitch and StreamElements tokens. I has able to get the jebait.net website to respond to chat after clearing the cookies (lock icon next to URL) and re-logging in. Wheel was also sending message after the relog. Please check and let me know you findings here or in the SE Discord. Thanks for the heads up.

**Comment by blinddesecrator** [comment]
It seems to have corrected today may have just been a hiccup for the day. Thanks for the response!
